modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
[[mods]]
modId="gmm"
version="1.2.5"
displayName="Ghostgames MineTopiaExtras Mod"
updateJSONURL="https://raw.githubusercontent.com/GhostgamesDHG/update.json/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minetopia-extra-mod"
logoFile="logo.png"
authors="GhostGamesDHG"
description='''
         This mod adds MineTopia money and more stuff!
'''